#配置日志级别
#配置根Logger及其日志输出目的地
#配置日志输出目的地 = 日志输出格式 日志消息格式 等
#配置日志级别
log4j.rootLogger=INFO,stdOut
#配置特定包的日志
log4j.logger.com.yq=INFO,myAppender

#配置日志输出目的地的输出方式 | 文件或控制台
# 控制台输出日志
log4j.appender.stdOut=org.apache.log4j.ConsoleAppender
#log4j.appender.myAppender=org.apache.log4j.ConsoleAppender
# 文件输出日志
#log4j.appender.myAppender=org.apache.log4j.FileAppender
#log4j.appender.myAppender.file=d:/log_file/test-log.log

log4j.appender.myAppender = org.apache.log4j.DailyRollingFileAppender
log4j.appender.myAppender.file = /opt/yq_tmp_log/log_file/log_
log4j.appender.myAppender.datePattern=yyyy-MM-dd'.log'
log4j.appender.myAppender.append = true

#配置日志输出目的地的输出格式 | 文本模式
log4j.appender.stdOut.layout=org.apache.log4j.PatternLayout
log4j.appender.stdOut.layout.conversionPattern=[%c] [%p] [%t] [%d] - %m%n

# 文件输出
log4j.appender.myAppender.layout=org.apache.log4j.PatternLayout
# 文件输出的日志格式
log4j.appender.myAppender.layout.conversionPattern=[%c] [%p] [%t] [%d] - %m%n
